Import("env")


env.Append(
    CPPPATH=[
        "#/",
        "#/lib",
        # Ugly hack
        Dir("../assets/compiled"),
    ],
)


libs = env.BuildModules(
    [
        "mlib",
        "stm32wb",
        "freertos",
        "print",
        "microtar",
        "mbedtls",
        "cli_util",
        "compress",
        "containers",
        "debug",
        "flipper_metadata",
        "pure",
        "signal_common",
        "srv_util",
        "storage_util",
        "libusb_stm32",
        "drivers",
        "fatfs",
        "flipper_format",
        "one_wire",
        "ibutton",
        "infrared",
        "subghz",
        "nfc",
        "digital_signal",
        "pulse_reader",
        "signal_reader",
        "u8g2",
        "lfrfid",
        "flipper_application",
        "music_worker",
        "mjs",
        "nanopb",
        "update_util",
        "heatshrink",
        "ble_profile",
        "datetime",
        "ieee754_parse_wrap",
    ],
)

Return("libs")
