#!/bin/sh
. /etc/rc.common

echo "PostInstall_Driver.command"

version=$( /usr/bin/sw_vers -productVersion )
major=$( awk -F'.' '{print $1}' <<< "${version}" )
minor=$( awk -F'.' '{print $2}' <<< "${version}" )
patch=$( awk -F'.' '{print $3}' <<< "${version}" )

sudo chmod -R 755 /System/Library/Extensions/RtWlanU.kext
sudo chmod -R 755 /System/Library/Extensions/RtWlanU1827.kext
sudo chmod -R 755 /System/Library/Extensions/RtWlanDisk.kext

sleep 1

sudo chown -R root:wheel /System/Library/Extensions/RtWlanU.kext
sudo chown -R root:wheel /System/Library/Extensions/RtWlanU1827.kext
sudo chown -R root:wheel /System/Library/Extensions/RtWlanDisk.kext


sudo chmod 644 /System/Library/Extensions/RtWlanU.kext/Contents/Info.plist
sudo chmod 644 /System/Library/Extensions/RtWlanU1827.kext/Contents/Info.plist
sudo chmod 644 /System/Library/Extensions/RtWlanDisk.kext/Contents/Info.plist

if [ "$minor" -ge 9 ]; then
		#echo 10.9~ =$minor

		sudo chmod 644 /System/Library/Extensions/RtWlanU.kext/Contents/_CodeSignature/CodeResources
		sudo chmod 644 /System/Library/Extensions/RtWlanU1827.kext/Contents/_CodeSignature/CodeResources
		sudo chmod 644 /System/Library/Extensions/RtWlanDisk.kext/Contents/_CodeSignature/CodeResources

elif [ "$minor" -ge 6 ] && [ "$minor" -le 8 ]; then
		sudo chmod 644 /System/Library/Extensions/RtWlanU.kext/Contents/MacOS/RtWlanU
		sudo chmod 644 /System/Library/Extensions/RtWlanU1827.kext/Contents/MacOS/RtWlanU1827
		sudo chmod 644 /System/Library/Extensions/RtWlanDisk.kext/Contents/MacOS/RtWlanDisk

fi


if [ "$minor" -eq 6 ]; then
	sudo kextcache -v 1 -a i386 -a x86_64 -m /System/Library/Caches/com.apple.kext.caches/Startup/Extensions.mkext /System/Library/Extensions

elif [ "$minor" -ge 7 ] && [ "$minor" -le 10 ]; then

	sudo kextcache -system-prelinked-kernel
	sudo kextcache -system-caches

fi


sudo touch /System/Library/Extensions

sudo kextload /System/Library/Extensions/RtWlanDisk.kext
sudo kextload /System/Library/Extensions/RtWlanU.kext
sudo kextload /System/Library/Extensions/RtWlanU1827.kext

echo "PostInstall_Driver Complete."