#!/bin/sh
. /etc/rc.common

echo "                                                                  "
echo "PreInstall_Driver.command"
FROM=`dirname "$0"`

echo "Unload Driver"
sudo kextunload /System/Library/Extensions/RtWlanU1827.kext
sudo kextunload /System/Library/Extensions/RtWlanU.kext
sudo kextunload /System/Library/Extensions/RtWlanDisk.kext


echo "Removing Driver..."
sudo rm -rf /System/Library/Extensions/RtWlanU1827.kext
sudo rm -rf /System/Library/Extensions/RtWlanU.kext
sudo rm -rf /System/Library/Extensions/RtWlanU_192.kext
sudo rm -rf /System/Library/Extensions/RtWlanDisk.kext
sudo rm -rf /System/Library/Extensions/RTL8192SU*.kext
sudo rm -rf /System/Library/Extensions/RTL8192CU*.kext
sudo rm -rf /System/Library/Extensions/RTL8188EU*.kext
sudo rm -rf /System/Library/Extensions/RTL8192EU*.kext
sudo rm -rf /System/Library/Extensions/RTL8192DU*.kext
sudo rm -rf /System/Library/Extensions/RtWlanU*.kext
sudo rm -rf /System/Library/Extensions/RTL8812AU*.kext
sudo rm -rf /Library/Extensions/RTL8812AU*.kext

echo "Removing Pkg"
sudo rm -rf /Library/Receipts/wlan.pkg
sudo rm -rf /Library/Receipts/wlanAc.pkg
sudo rm -rf /Library/Receipts/rtl8192SU4.pkg
sudo rm -rf /Library/Receipts/rtl8192CU4.pkg
sudo rm -rf /Library/Receipts/rtl8188EU4.pkg
sudo rm -rf /Library/Receipts/rtl8192EU4.pkg
sudo rm -rf /Library/Receipts/rtl8192DU4.pkg
sudo rm -rf /Library/Receipts/rtl8812AU4.pkg
sudo rm -rf /Library/Receipts/wireless-acNetworkUtility.pkg
sudo rm -rf /Library/Receipts/wirelessNetworkUtility.pkg



echo "Checking Preferences"

_PREFERENCE="/Library/Preferences/SystemConfiguration/preferences.plist"
_NETWORKINTERFACES="/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist"

# Phase 1: Get CurrentSet UUID
autoUuid=`/usr/libexec/Plistbuddy -c "Print :Sets" $_PREFERENCE | grep -B1 -m1 Automatic | grep Dict | awk '{ print $1 }'`
echo autoUuid =$autoUuid

# Phase 2: Get All Services Array
NetServicesArray=`/usr/libexec/PlistBuddy -c "Print :NetworkServices" $_PREFERENCE | egrep '[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}' -o`
echo NetServicesArray =$NetServicesArray

for eNetService in $NetServicesArray
do
	echo eNetService =$eNetService
	eIntf=`/usr/libexec/Plistbuddy -c "Print :NetworkServices:$eNetService" $_PREFERENCE | grep -a "DeviceName" | awk '{ print $3 }'` 
	echo eIntf =$eIntf
	bHit=`/usr/libexec/Plistbuddy -c "Print :Interfaces" $_NETWORKINTERFACES | grep -a -A7 'RtWlanU\|RTL8812AU\|RTL8192CU\|RTL8188EU\|RTL8192EU' | grep -a "BSD Name"| awk '{ print $4 }'| grep -aw $eIntf`
	
	# -z: string is null, that is, has zero length
	# -n: string is not null
	if [ -n "${bHit}" ]; then
		echo bHit =$bHit
		
		# Phase 3: Check interface down : Sets:$autoUuid:Network:Service:UUID
		bIfconfigDown=`/usr/libexec/Plistbuddy -c "Print :Sets:$autoUuid:Network:Service:$eNetService" $_PREFERENCE`
				
		if [ -z "${bIfconfigDown}" ]; then
			echo bIfconfigDown=$bIfconfigDown

			# Phase 4: Remove NetworksServices:UUID
			sudo /usr/libexec/PlistBuddy -c "delete :NetworkServices:$eNetService dict" $_PREFERENCE
		fi
	fi
done


version=$( /usr/bin/sw_vers -productVersion )
major=$( awk -F'.' '{print $1}' <<< "${version}" )
minor=$( awk -F'.' '{print $2}' <<< "${version}" )
patch=$( awk -F'.' '{print $3}' <<< "${version}" )

if [ "$major" -eq 10 ]; then
	echo major =$major
	
	if [ "$minor" -ge 11 ]; then
		#echo 10.11~ =$minor
		sudo touch /System/Library/Extensions
	fi

	#if [ "$minor" -ge 13 ]; then
		#echo 10.13~ =$minor
		#sudo spctl --master -disable
	#fi
fi


echo "PreInstall_Driver Complete."