name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ created ]

env:
  XCODE_VERSION: '16.0'
  MACOS_VERSION: 'macos-14'

jobs:
  lint:
    name: Lint Code
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SwiftLint
        run: brew install swiftlint
      
      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
      
      - name: Install swift-format
        run: brew install swift-format
      
      - name: Check formatting
        run: |
          find RTL8814AUDriver -name "*.swift" -print0 | xargs -0 swift-format lint --strict

  build:
    name: Build Driver
    runs-on: macos-14
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Show Swift version
        run: swift --version
      
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Build driver (Debug)
        run: |
          xcodebuild \
            -project RTL8814AUDriver.xcodeproj \
            -scheme RTL8814AUDriver \
            -configuration Debug \
            -derivedDataPath DerivedData \
            clean build
      
      - name: Build driver (Release)
        run: |
          xcodebuild \
            -project RTL8814AUDriver.xcodeproj \
            -scheme RTL8814AUDriver \
            -configuration Release \
            -derivedDataPath DerivedData \
            clean build
      
      - name: Find built driver
        id: find-driver
        run: |
          DEXT_PATH=$(find DerivedData -name "*.dext" -type d | head -n 1)
          echo "dext_path=$DEXT_PATH" >> $GITHUB_OUTPUT
          echo "Found driver at: $DEXT_PATH"
      
      - name: Verify driver bundle
        run: |
          if [ -z "${{ steps.find-driver.outputs.dext_path }}" ]; then
            echo "Error: Driver not found"
            exit 1
          fi
          
          echo "Checking Info.plist..."
          plutil -lint "${{ steps.find-driver.outputs.dext_path }}/Contents/Info.plist"
          
          echo "Checking executable..."
          file "${{ steps.find-driver.outputs.dext_path }}/Contents/MacOS/RTL8814AUDriver"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RTL8814AUDriver-${{ github.sha }}
          path: ${{ steps.find-driver.outputs.dext_path }}
          retention-days: 30

  test:
    name: Run Tests
    runs-on: macos-14
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      
      - name: Run tests
        run: swift test --parallel
      
      - name: Generate code coverage
        if: github.event_name == 'pull_request'
        run: |
          swift test --enable-code-coverage
          xcrun llvm-cov export \
            .build/debug/RTL8814AUDriverPackageTests.xctest/Contents/MacOS/RTL8814AUDriverPackageTests \
            -instr-profile .build/debug/codecov/default.profdata \
            -format="lcov" > coverage.lcov
      
      - name: Upload coverage to Codecov
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: false

  security:
    name: Security Checks
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run security audit
        run: |
          # Check for common security issues
          echo "Checking for hardcoded credentials..."
          ! grep -r "password\|secret\|token" RTL8814AUDriver --include="*.swift" || exit 1
          
          echo "Checking for TODO security items..."
          grep -r "TODO.*security\|FIXME.*security" RTL8814AUDriver --include="*.swift" || true

  documentation:
    name: Build Documentation
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check markdown files
        run: |
          # Verify all markdown files are valid
          for file in *.md; do
            echo "Checking $file"
            # Basic validation - file should exist and be readable
            test -r "$file"
          done
      
      - name: Generate Swift documentation
        run: |
          # Install swift-docc if available
          if swift package plugin --list | grep -q "generate-documentation"; then
            swift package generate-documentation
          else
            echo "DocC not available, skipping"
          fi

  release:
    name: Create Release
    runs-on: macos-14
    needs: [build, test]
    if: github.event_name == 'release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Make scripts executable
        run: chmod +x build.sh sign.sh install.sh
      
      - name: Build release
        run: ./build.sh
      
      - name: Create distribution archive
        run: |
          cd build
          tar -czf RTL8814AUDriver-Release.tar.gz Distribution/
          cd ..
      
      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 build/RTL8814AUDriver-Release.tar.gz | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "SHA256: $SHA256"
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/RTL8814AUDriver-Release.tar.gz
          asset_name: RTL8814AUDriver-Release.tar.gz
          asset_content_type: application/gzip
      
      - name: Update Homebrew formula
        run: |
          echo "Update Homebrew formula with SHA256: ${{ steps.sha256.outputs.sha256 }}"
          # In a real setup, this would commit to the Homebrew tap repository

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [lint, build, test, security]
    if: always()
    
    steps:
      - name: Check workflow status
        run: |
          if [ "${{ needs.lint.result }}" == "success" ] && \
             [ "${{ needs.build.result }}" == "success" ] && \
             [ "${{ needs.test.result }}" == "success" ] && \
             [ "${{ needs.security.result }}" == "success" ]; then
            echo "✅ All checks passed!"
          else
            echo "❌ Some checks failed"
            exit 1
          fi
