#!/bin/sh
. /etc/rc.common

kill_item()
{
	process_name="$1"
	#echo "\n[kill_item]:: $process_name"
	pid=$(ps -A | grep "$process_name" |grep -v grep| awk '{print $1}')
	if [ "$pid" ]; then
		#echo "\tkillall::$process_name"
		sudo killall -c "$process_name"
	fi
}

remove_file()
{
	file_name="$1"
	#echo "\n[remove_file]:: $file_name"
	if [ -e "$file_name" ]; then
		#echo "\trm::$file_name"
		sudo rm -rf "$file_name"
	fi
}

remove_directory()
{
	dir_name="$1"
	#echo "\n[remove_directory]:: $dir_name"
	if [ -d "$dir_name" ]; then
		#echo "\trm_dir::$dir_name"
		sudo rm -rf "$dir_name"
	fi
}

unload_driver()
{
	kext_name="$1"
	bundle_id=com.realtek.driver.$1
	#echo "\n[unload_driver]:: $bundle_id"

	index=$(kextstat -b $bundle_id |grep $bundle_id | awk '{print $1}')
	if [ "$index" ]; then
		#echo "\tkextunload::$kext_name"
		#sudo kextunload -c "$kext_name"

		if [ -e "/System/Library/Extensions/$kext_name.kext" ]; then
			sudo kextunload "/System/Library/Extensions/$kext_name.kext"
			sleep 2
		fi

		if [ -e "/Library/Extensions/$kext_name.kext" ]; then
			sudo kextunload "/Library/Extensions/$kext_name.kext"
			sleep 2
		fi

	fi
}

remove_wildcard_file()
{
	wildcard_file=$1
	#echo "\n[remove_wildcard_file]:: $wildcard_file"
	for efile in $wildcard_file ; do
		#echo "\tefile: $efile"
		sudo rm -rf "$efile"
	done
}

echo "                                                                  "
echo "Please type the password of \"root\" to Uninstall ..."
FROM=`dirname "$0"`

echo "\nPhase: Terminate Utility"
kill_item "Wireless-AC Network Utility"
kill_item "Wireless Network Utility"
kill_item "TP-LINK Wireless Configuration Utility"
kill_item "BearExtender"
kill_item "wpa_supplicant"
kill_item "StatusBarApp"
sleep 2

echo "Phase3: Remove Utility Related"

# Wlan.Software / WlanAC104.Software / WlanAC.Software / Wlan104.Software
remove_wildcard_file "/Library/LaunchAgents/Wlan*.Software"

remove_file "/Library/LaunchAgents/WlanAC.plist"
remove_file "/Library/LaunchAgents/Wlan.Software.plist"
remove_file "/Library/LaunchDaemons/Wlan.SoftwareDaemon"
remove_file "/Library/LaunchDaemons/Wlan.SoftwareDaemon.plist"

# "Removing Socket Files"
remove_file "/var/tmp/com.realtek.utility.statusbar.socket"
remove_file "/var/tmp/com.realtek.utility.daemon.socket"

remove_wildcard_file "/Users/*/Library/Preferences/com.realtek.*"
remove_wildcard_file "/Users/*/Library/Preferences/StatusBarApp.plist"
remove_wildcard_file "/var/tmp/com.realtek.utility.*"
remove_directory "/Library/Application Support/WLAN"


kill_item "RtWlanHelper"
	
# Legacy Utility
remove_directory "/System/Library/CoreServices/StatusBarApp.app"
remove_directory "/Applications/Wireless-AC Network Utility.app"
remove_directory "/Applications/Wireless Network Utility.app"
remove_directory "/Applications/TP-LINK Wireless Configuration Utility.app"
remove_directory "/Applications/BearExtender.app"

echo "Phase4: Remove Install Log"
remove_wildcard_file "/private/var/db/receipts/com.realtek.*"
remove_wildcard_file "/private/var/db/receipts/com.Wlan.*"
remove_wildcard_file "/private/var/db/receipts/com.wlan.*"
remove_wildcard_file "/private/var/db/receipts/com.Wireless*.*"
remove_wildcard_file "/private/var/db/receipts/com.*Utility*.pkg.*"
remove_wildcard_file "/private/var/db/receipts/com.*StatusBarApp.*"
remove_wildcard_file "/private/var/db/receipts/com.*StartUp.pkg.*"
remove_wildcard_file "/private/var/db/receipts/com.*Driver*.pkg.*"
remove_wildcard_file "/private/var/db/receipts/com.UnPref.*"
remove_wildcard_file "/private/var/db/receipts/com.BearExtender.*"
remove_wildcard_file "/private/var/db/receipts/com.bearextenderturbo.*"


echo "Phase5: Removing Driver"

unload_driver "RtWlanU1827"
unload_driver "RtWlanU"
unload_driver "RtWlanDisk"
unload_driver "RTL8812AU"
unload_driver "RTL8192SU"
unload_driver "RTL8192CU"
unload_driver "RTL8188EU"
unload_driver "RTL8192EU"
unload_driver "RTL8192DU"
unload_driver "RTL8723BU"

#RtWlanU.kext / RtWlanU1827.kext / RtWlanU_192.kext / RtWlanDisk.kext
remove_wildcard_file "/System/Library/Extensions/RtWlan*.kext"

#Recovery Mode
#remove_wildcard_file "/Library/StagedExtensions/System/Library/Extensions/RtWlan*.kext"
#remove_wildcard_file "/Library/StagedExtensions/Library/Extensions/RtWlan*.kext"
#remove_wildcard_file "/Library/StagedExtensions/tmp/RtWlan*.kext"

#RTL8192SU* / RTL8192CU* / RTL8192DU* / RTL8188EU* / 
#RTL8192EU* / RTL8723BU* / RTL8812AU*
remove_wildcard_file "/System/Library/Extensions/RTL8*.kext"

#For BearExtender
remove_wildcard_file "/Library/Extensions/RTL8812AU*.kext"

echo "Phase: System Information"
# Usage: Plistbuddy [-cxh] <file.plist>
#    -c "<command>" execute command, otherwise run in interactive mode
#
#
# A.plist
# Dict{
# 	KeyA=ValueA
#	KeyB=ValueB
#	KeyC=ValueC
# }
# /usr/libexec/Plistbuddy -c "Print" A.plist (print A.plist content)
# /usr/libexec/Plistbuddy -c "Print KeyA" A.plist (get ValueA)
# /usr/libexec/Plistbuddy -c "merge A.plist" B.plist (merge A.plist to B)
#
# /usr/libexec/Plistbuddy -c "Print Sets" preferences.plist 
# (Get Sets value: UUID)
#

# grep: print lines matching a pattern
# 	-B NUM, --before-context=NUM
#        Print NUM lines of leading context before matching lines.  
#	 Places a line containing -- between  contiguous groups of matches.
#

_PREFERENCE="/Library/Preferences/SystemConfiguration/preferences.plist"
_NETWORKINTERFACES="/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist"

#_PREFERENCE="/Users/MAC/Airport_Style/Utility_Project/Reference/10.6/preferences.plist"
#_NETWORKINTERFACES="/Users/MAC/Airport_Style/Utility_Project/Reference/10.6/NetworkInterfaces.plist"

# Phase 1: Get CurrentSet UUID
autoUuid=`/usr/libexec/Plistbuddy -c "Print :Sets" $_PREFERENCE | grep -B1 -m1 Automatic | grep Dict | awk '{ print $1 }'`
# FA49A453-0318-4E12-A7D3-9AD011E02B3A
echo autoUuid =$autoUuid

# Phase 2: Get Realtek Interfaces Array

# use Plistbuddy open plist, the field order is different from TextEdit or Property List Editor
# Active->IOPathMatch->IOMACAddress->IOInterfaceUnit->IOBuiltin->SCNetworkInterfaceType->IOInterfaceType->BSD Name->SCNetworkInterfaceInfo
# for debug
RtWlanArray=`/usr/libexec/Plistbuddy -c "Print :Interfaces" $_NETWORKINTERFACES | grep -a -A7 'RtWlanU\|RTL8812AU\|RTL8192CU\|RTL8188EU\|RTL8192EU' | grep -a "BSD Name"| awk '{ print $4 }'`
echo RtWlanArray =$RtWlanArray
#RtWlanArray =en6 en7 en9 en10 en18 en26


# Phase 3: Get All Services Array
NetServicesArray=`/usr/libexec/PlistBuddy -c "Print :NetworkServices" $_PREFERENCE | egrep '[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}' -o`
echo NetServicesArray =$NetServicesArray

for eNetService in $NetServicesArray
do
	echo eNetService =$eNetService
	eIntf=`/usr/libexec/Plistbuddy -c "Print :NetworkServices:$eNetService" $_PREFERENCE | grep -a "DeviceName" | awk '{ print $3 }'` 
	echo eIntf =$eIntf
	bHit=`/usr/libexec/Plistbuddy -c "Print :Interfaces" $_NETWORKINTERFACES | grep -a -A7 'RtWlanU\|RTL8812AU\|RTL8192CU\|RTL8188EU\|RTL8192EU' | grep -a "BSD Name"| awk '{ print $4 }'| grep -aw $eIntf`
	
	# -z: string is null, that is, has zero length
	# -n: string is not null
	if [ -n "${bHit}" ]; then
		echo bHit =$bHit
	
		# Phase 4: Remove NetworksServices:UUID
		sudo /usr/libexec/PlistBuddy -c "delete :NetworkServices:$eNetService dict" $_PREFERENCE

		# Phase 5: Remove Sets:$autoUuid:Network:Service:UUID
		sudo /usr/libexec/PlistBuddy -c "delete :Sets:$autoUuid:Network:Service:$eNetService dict" $_PREFERENCE

		# Phase 6: Remove Sets:$autoUuid:Network:Global:IPv4:ServiceOrder:UUID
		# Because we would delete serverOrder, it must be queried every time.
		serverOrderArray=`/usr/libexec/PlistBuddy -c "Print :Sets:$autoUuid:Network:Global:IPv4:ServiceOrder" $_PREFERENCE | grep -v "Array" | grep -v "}"`
		#echo serverOrderArray =$serverOrderArray

		idx=0
		bFind=0
		for eServiceOrd in $serverOrderArray
		do
			#echo eServiceOrd =$eServiceOrd
			if [ "${eServiceOrd}" == "${eNetService}" ]; then
				bFind=1
				break
			fi
			idx=`expr $idx + 1`
		done

		if [ "${bFind}" -eq 1 ]; then
			echo idx=$idx
			sudo /usr/libexec/PlistBuddy -c "delete :Sets:$autoUuid:Network:Global:IPv4:ServiceOrder:$idx" $_PREFERENCE
		fi
	fi
done

#scselect


echo "Uninstall Complete."
